// The pane backdrop runs the shader library's fragment shaders on the phone, and
// they read what its vertex shader computes. The library does not export that
// shader, so it is copied out of the installed package on install; not committed.
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const app = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const source = resolve(app, "node_modules/@paper-design/shaders/dist/vertex-shader.js");
const { vertexShaderSource } = await import(pathToFileURL(source).href);
writeFileSync(
  resolve(app, "src/ui/vertexShader.generated.ts"),
  `// Generated by scripts/generate-shaders.mjs from @paper-design/shaders.\nexport const vertexShaderSource = ${JSON.stringify(vertexShaderSource)};\n`,
);
