// Generated by server/protocol/scripts/generate.mjs from server/protocol/schema.
// Do not edit by hand.

use serde::{Deserialize, Serialize};

/// The body of every response that is not a success.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ApiError {
    pub error: ErrorDetail,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ErrorCode {
    #[serde(rename = "bad_request")]
    BadRequest,
    #[serde(rename = "unauthorized")]
    Unauthorized,
    #[serde(rename = "forbidden")]
    Forbidden,
    #[serde(rename = "not_found")]
    NotFound,
    #[serde(rename = "conflict")]
    Conflict,
    #[serde(rename = "payload_too_large")]
    PayloadTooLarge,
    #[serde(rename = "rate_limited")]
    RateLimited,
    #[serde(rename = "internal")]
    Internal,
    #[serde(rename = "unavailable")]
    Unavailable,
    /// A value added after this build, which it cannot act on.
    #[serde(other)]
    Unknown,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ErrorDetail {
    pub code: ErrorCode,
    /// Written for whoever reads the logs. Apps show their own words for each code.
    pub message: String,
    /// The same as the response's x-request-id header, and how the server's logs find this request.
    pub request_id: String,
}

/// Whether the API can serve requests, and which build is answering.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Health {
    pub status: HealthStatus,
    pub database: HealthStatus,
    /// The commit the running build was made from, or "dev".
    pub version: String,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum HealthStatus {
    #[serde(rename = "ok")]
    Ok,
    #[serde(rename = "unavailable")]
    Unavailable,
    /// A value added after this build, which it cannot act on.
    #[serde(other)]
    Unknown,
}

/// Reads `json` as the named type and writes it back, for the contract tests.
#[cfg(test)]
pub(crate) fn round_trip(name: &str, json: &str) -> Option<super::RoundTrip> {
    use super::through;
    Some(match name {
        "ApiError" => through::<ApiError>(json),
        "ErrorCode" => through::<ErrorCode>(json),
        "ErrorDetail" => through::<ErrorDetail>(json),
        "Health" => through::<Health>(json),
        "HealthStatus" => through::<HealthStatus>(json),
        _ => return None,
    })
}
